language: rust
rust:
  - nightly-2019-05-11

before_script: |
  rustup component add rustfmt clippy
script: |
  cargo fmt --all -- --check &&
  cargo clippy --all --all-targets -- -D warnings &&
  cargo build --no-default-features --verbose &&
  cargo build --all --verbose &&
  cargo test  --all --verbose
