[package]
name = "async-compression"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>", "Allen Bui <fairingrey@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["compression", "gzip", "zstd", "brotli", "async"]
categories = ["compression", "asynchronous"]
repository = "https://github.com/rustasync/async-compression"
description = """
Adaptors between compression crates and Rust's modern asynchronous IO types.
"""

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
# groups
default = []
all = ["all-implementations", "all-algorithms"]
all-implementations = ["bufread", "write", "stream"]
all-algorithms = ["brotli", "bzip", "deflate", "gzip", "zlib", "zstd"]

# implementations
bufread = ["futures-io"]
write = ["futures-io"]
stream = ["bytes"]

# algorithms
brotli = ["brotli2"]
bzip = ["bzip2"]
deflate = ["flate2"]
gzip = ["flate2"]
zlib = ["flate2"]
zstd = ["libzstd", "zstd-safe"]

[dependencies]
brotli2 = { version = "0.3.2", optional = true }
bytes = { version = "0.4.12", optional = true }
bzip2 = { version = "0.3.3" , optional = true }
flate2 = { version = "1.0.11", optional = true }
futures-core = { version = "0.3.0", default-features = false }
futures-io = { version = "0.3.0", default-features = false, features = ["std"], optional = true }
pin-project = "0.4.3"
libzstd = { version = "0.5.0", optional = true, package = "zstd", default-features = false }
zstd-safe = { version = "2.0.0", optional = true, default-features = false }
memchr = "2.2.1"

[dev-dependencies]
proptest = "0.9.4"
proptest-derive = "0.1.2"
rand = "0.7.2"
futures = "0.3.0"
futures-test = "0.3.0"
ntest = "0.3.3"
timebomb = "0.1.2"

[[test]]
name = "brotli"
required-features = ["all-implementations", "brotli"]

[[test]]
name = "bzip"
required-features = ["all-implementations", "bzip"]

[[test]]
name = "deflate"
required-features = ["all-implementations", "deflate"]

[[test]]
name = "gzip"
required-features = ["all-implementations", "gzip"]

[[test]]
name = "zlib"
required-features = ["all-implementations", "zlib"]

[[test]]
name = "zstd"
required-features = ["all-implementations", "zstd"]

[[test]]
name = "proptest"
required-features = ["all"]
