[package]
name = "async-compression"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>", "Allen Bui <fairingrey@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
brotli2 = "0.3.2"
bytes = "0.4.12"
flate2 = "1.0.7"
futures-preview = "0.3.0-alpha.16"
pin-project = "0.3.2"
zstd = "0.4"
zstd-safe = "1.4"

[dev-dependencies]
proptest = "0.9.3"
pin-utils = "0.1.0-alpha.4"
proptest-derive = "0.1.1"
rand = "0.6.5"
futures-test-preview = "0.3.0-alpha.16"
